# Generated by Django 2.2.2 on 2019-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('F', 'FUPRE'), ('U', 'UNIBEN'), ('P', 'UNIPORT')], max_length=1)),
            ],
        ),
    ]
