# Generated by Django 2.2.2 on 2019-07-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190712_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
    ]
