# Generated by Django 2.2.2 on 2019-07-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_school_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
